import type { Activity, Game, Post } from "@/lib/types";

export const socialLinks = {
  instagram: "https://www.instagram.com/dkbhmg/",
  whatsapp: "https://chat.whatsapp.com/FEH19lTq3LIJDWBzBDkE7J",
  youtube: process.env.NEXT_PUBLIC_YOUTUBE_URL || "",
};

export const demoActivities: Activity[] = [
  {
    id: "demo-1",
    title: "Treino aberto do DK",
    starts_at: "2026-09-20T09:00:00-03:00",
    location: "Parque Ecológico da Pampulha — Belo Horizonte",
    type: "Treino",
    status: "confirmado",
    description: "Treino técnico, jogos e integração com novos participantes.",
  },
  {
    id: "demo-2",
    title: "Atividade especial",
    starts_at: "2026-09-27T09:00:00-03:00",
    location: "A definir",
    type: "Atividade interna",
    status: "a_definir",
    description: "Detalhes serão publicados no cronograma.",
  },
];

export const games: Game[] = [
  {
    id: "captura-bandeira",
    name: "Captura da Bandeira",
    summary: "Duas equipes tentam capturar a bandeira adversária enquanto defendem a própria base.",
    objective: "Capturar a bandeira adversária e levá-la até a própria base, protegendo ao mesmo tempo a bandeira da sua equipe.",
    teamFormation: "Duas equipes com quantidade de participantes definida pela organização.",
    rules: [
      "Cada participante possui 1 pontos de vida.",
      "Para conquistar a vitória por captura, as duas bandeiras devem estar juntas dentro da base da equipe.",
      "Também é possível vencer eliminando completamente a equipe adversária.",
      "Os participantes devem respeitar os limites e as áreas determinadas para cada base.",
    ],
    victory: "A rodada termina quando uma equipe reúne as duas bandeiras em sua base ou elimina todos os adversários. Em partidas com várias rodadas, vence quem acumular mais vitórias.",
    equipment: "Espadas, escudos, lanças, duais, arquearia e demais equipamentos autorizados pela organização.",
    safety: "As bases e os limites do campo devem ser claramente identificados. A bandeira não pode ser utilizada como equipamento de ataque ou defesa.",
  },
  {
    id: "Trollball",
    name: "Trollball",
    summary: "Jogo de avanço territorial em que as equipes disputam a posse do Troll e tentam levá-lo até o poço adversário.",
    objective: "Conduzir a Cabeça de Troll até o poço adversário e marcar a maior quantidade possível de pontos.",
    teamFormation: "Cada equipe pode possuir até 5 combatentes e 2 curandeiros em campo.",
    rules: [
      "A Cabeça de Troll começa no centro do campo.",
      "Cada participante possui 1 ponto de vida.",
      "Ela deve ser transportada e passada entre os jogadores, nunca arremessada.",
      "Combatentes atingidos devem se ajoelhar e aguardar a atuação de um curandeiro.",
      "Curandeiros não utilizam equipamentos de combate e podem recuperar jogadores eliminados.",
      "O ponto somente é válido quando o Troll é colocado corretamente no poço adversário e anunciado.",
      "Após cada ponto, todos retornam às posições iniciais.",
    ],
    victory: "Vence a equipe que marcar a maior quantidade de Trolls ao término da partida.",
    equipment: "Equipamentos de combate de até 90 cm, dentro dos padrões estabelecidos pela organização.",
    safety: "Não é permitido contato físico direto. Os limites do campo devem ser respeitados e qualquer jogador atingido deve interromper imediatamente sua participação até ser recuperado.",
  },
  {
    id: "batalha-campal",
    name: "Batalha Campal",
    summary: "Combate coletivo que trabalha formação, posicionamento e comunicação.",
    objective: "Eliminar a equipe adversária ou cumprir o objetivo especial da rodada.",
    teamFormation: "Duas ou mais equipes equilibradas de acordo com o número de participantes disponíveis.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "Ao perder o ponto de vida, o jogador deve deixar a área de combate e seguir para o campo dos eliminados.",
      "Não há retorno ao combate durante a mesma rodada, salvo quando a organização definir uma regra diferente.",
    ],
    victory: "Vence a última equipe que possuir combatentes ativos no campo.",
    equipment: "Espadas, escudos, lanças, duais, arquearia e demais equipamentos autorizados pela organização.",
    safety: "Combatentes eliminados devem sair imediatamente da área ativa e aguardar em local seguro até o encerramento da rodada.",
  },
    {
    id: "Archery-Tag",
    name: "Archery Tag",
    summary: "Duas equipes se enfrentam com arco e flecha, buscando eliminar adversários e acertar os alvos da equipe rival.",
    objective: "Eliminar adversários e acertar os alvos da equipe adversária dentro do tempo da partida.",
    teamFormation: "Duas equipes com até 5 participantes cada, distribuídas em lados opostos do campo.",
    rules: [
      "Todas as flechas começam posicionadas no centro do campo.",
      "Ao sinal, os participantes avançam para recolher as flechas.",
      "Cada jogador possui 1 ponto de vida.",
      "Ao ser atingido, o participante deixa temporariamente a partida.",
      "Jogadores eliminados podem retornar caso sua equipe acerte um dos alvos determinados.",
    ],
    victory: "Vence a equipe que eliminar mais adversários ou derrubar a maior quantidade de alvos ao final do tempo determinado.",
    equipment: "Somente arcos e flechas próprios para Archery Tag, devidamente adaptados aos padrões de segurança da atividade.",
    safety: "Respeitar os limites do campo, as orientações da arbitragem e utilizar somente equipamentos previamente aprovados.",
  },
    {
    id: "Guerra-pelas-Fitas",
    name: "Guerra-pelas-Fitas",
    summary: "Equipes disputam fitas espalhadas pelo campo e podem conquistar novas fitas ao derrotar adversários.",
    objective: "Coletar e conquistar a maior quantidade possível de fitas espalhadas pelo campo.",
    teamFormation: "Equipes formadas normalmente por 4 ou 5 participantes.",
    rules: [
      "Cada participante possui 1 ponto de vida..",
      "As fitas podem ser encontradas pelo campo ou conquistadas ao derrotar adversários.",
      "As fitas de um jogador eliminado ficam com quem aplicou o golpe final..",
      "Não é permitido trocar, doar ou abandonar fitas..",
      "As fitas não podem ser utilizadas como equipamento de ataque ou defesa.",
    ],
    victory: "Vence a equipe que possuir a maior quantidade de fitas ao final do tempo e ainda tiver pelo menos um jogador em condições de combate.",
    equipment: "Equipamentos autorizados pela organização e dentro dos padrões de segurança",
    safety: "As fitas devem ficar em locais visíveis e acessíveis. Não é permitido utilizar obstáculos perigosos ou esconder fitas em locais que ofereçam risco aos participantes.",
  },
    {
    id: "Batalha-de-Campo-com-Conquista",
    name: "Batalha de Campo com Conquista",
    summary: "Combate estratégico em larga escala no qual as equipes precisam proteger sua liderança e eliminar os comandantes adversários.",
    objective: "Derrotar a estrutura de comando das equipes adversárias, eliminando líderes e capitães.",
    teamFormation: "Equipes com 11 ou mais participantes, organizadas entre líder, capitães e combatentes.",
    rules: [
      "Cada equipe possui 1 líder com 5 pontos de vida.",
      "Cada equipe possui 2 capitães com 3 pontos de vida cada.",
      "Os demais combatentes possuem 1 pontos de vida.",
      "A estratégia deve considerar a proteção da liderança e o avanço contra os comandantes adversários..",
    ],
    victory: "Vence a equipe que eliminar as forças adversárias e sua estrutura de liderança.",
    equipment: "Equipamentos previamente autorizados e distribuídos conforme o equilíbrio definido pela organização.",
    safety: "Todos devem respeitar as áreas válidas de acerto, os pontos de vida e as orientações da arbitragem durante toda a batalha.",
  },
    {
    id: "Mate-o-Rei",
    name: "Mate o Rei",
    summary: "Cada equipe deve proteger seu Rei enquanto organiza ataques para eliminar os Reis adversários.",
    objective: "Proteger o próprio Rei enquanto a equipe tenta eliminar o Rei adversário.",
    teamFormation: "Duas ou mais equipes, cada uma formada por um Rei e seus combatentes.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "Antes da partida, cada equipe deve definir quem exercerá a função de Rei.",
      "Os jogadores devem organizar estratégias de ataque e defesa.",
      "A eliminação do Rei representa a derrota da equipe naquela rodada.",
    ],
    victory: "Vence a última equipe que mantiver seu Rei em condições de combate ou que eliminar todos os Reis adversários.",
    equipment: "Equipamentos autorizados pela organização e adequados aos padrões",
    safety: "A função de Rei não altera as regras gerais de combate. Todos os participantes continuam sujeitos aos mesmos critérios de segurança.",
  },
    {
    id: "Rapto-da-Princesa",
    name: "Rapto da Princesa",
    summary: "Uma equipe protege a Princesa enquanto a outra tenta capturá-la e mantê-la sob seu domínio.",
    objective: "Proteger a Princesa ou conquistá-la e mantê-la sob controle até o encerramento da partida.",
    teamFormation: "Uma equipe de defesa e uma equipe de raptores, com quantidade de participantes definida pela organização.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "Uma equipe inicia responsável pela proteção da Princesa.",
      "Ao tocar na Princesa, o jogador passa a conduzi-la.",
      "A equipe atacante deve conseguir levá-la para sua área de domínio enquanto os defensores tentam recuperá-la.",
    ],
    victory: "Vence a equipe que estiver com a posse da Princesa ao término do tempo estabelecido.",
    equipment: "Equipamentos previamente autorizados para a atividade.",
    safety: "A pessoa que representa a Princesa não deve sofrer golpes nem contato físico durante a disputa. A interação com ela deve ocorrer somente conforme as regras definidas antes da partida.",
  },
    {
    id: "Defesa-da-Vila",
    name: "Defesa da Vila",
    summary: "Desafio individual de arquearia em que o participante deve acertar diferentes alvos no menor tempo possível.",
    objective: "Atingir todos os alvos utilizando o menor número possível de tentativas e no menor tempo.",
    teamFormation: "Atividade individual, com um participante por vez.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "O participante dispõe de 5 flechas.",
      "Deve acertar 3 alvos diferentes.",
      "Os disparos devem ser realizados dentro da área de tiro demarcada.",
      "O participante pode escolher sua posição de tiro, desde que não ultrapasse os limites estabelecidos.",
    ],
    victory: "Vence quem atingir os três alvos no menor tempo, respeitando o limite de flechas disponível.",
    equipment: "Arco e flechas adaptados aos padrões de segurança da arquearia do DK.",
    safety: "A área de tiro deve permanecer isolada e ninguém pode acessar a zona dos alvos enquanto houver um arqueiro realizando disparos.",
  },
    {
    id: "Duelo-de-Arqueiros",
    name: "Duelo de Arqueiros",
    summary: "Dois arqueiros se enfrentam em uma disputa de precisão, esquiva e controle de disparos.",
    objective: "Acertar o adversário mais vezes durante as séries de disparos.",
    teamFormation: "Duelo individual entre dois arqueiros.",
    rules: [
      "Cada arqueiro possui 1 ponto de vida por rodada.",
      "Cada participante inicia com 5 flechas.",
      "Os arqueiros permanecem dentro das posições previamente demarcadas.",
      "É permitido esquivar o corpo, mas não abandonar a posição definida.",
      "O arco não pode ser utilizado como escudo.",
      "Após o término das flechas, uma nova série pode ser iniciada",
    ],
    victory: "Vence o participante que acumular a maior quantidade de acertos ao término do tempo.",
    equipment: "Arcos e flechas adaptados aos padrões de segurança",
    safety: "A distância mínima entre os participantes deve ser definida pela organização e somente flechas aprovadas podem ser utilizadas.",
  },
    {
    id: "Batalha-de-Cerco",
    name: "Batalha de Cerco",
    summary: "Uma equipe fortificada tenta resistir enquanto uma força numericamente superior busca romper suas defesas.",
    objective: "Os defensores devem proteger sua posição pelo tempo determinado, enquanto os atacantes tentam romper a defesa.",
    teamFormation: "Entre 5 e 15 defensores contra uma força atacante que pode possuir aproximadamente o dobro de participantes.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "Os defensores permanecem dentro ou próximos da área estabelecida como fortificação.",
      "Os atacantes devem avançar contra a posição defensiva.",
      "Os equipamentos devem ser distribuídos de forma equilibrada entre as equipes.",
    ],
    victory: "Os defensores vencem se resistirem até o término do tempo. Os atacantes vencem caso eliminem a defesa ou conquistem a área antes do encerramento.",
    equipment: "Equipamentos autorizados pela organização, buscando manter equilíbrio entre ataque e defesa.",
    safety: "A área do cerco deve ser delimitada previamente, evitando obstáculos perigosos e garantindo espaço suficiente para movimentação dos participantes.",
  },
    {
    id: "Rei-da-Mesa",
    name: "Rei da Mesa",
    summary: "Combates individuais e consecutivos em que o vencedor permanece na arena enfrentando novos adversários.",
    objective: "Permanecer na arena pelo maior tempo possível, derrotando sucessivamente outros combatentes.",
    teamFormation: "Atividade individual em sistema de fila, com dois participantes combatendo por vez.",
    rules: [
      "Cada participante possui 1 ponto de vida.",
      "Um combatente permanece como Rei da Mesa enquanto continuar vencendo seus adversários.",
      "Ao ser eliminado, o jogador deixa a arena e retorna ao final da fila.",
      "O próximo participante assume imediatamente o combate.",
    ],
    victory: "Vence ou se destaca o combatente que conseguir derrotar a maior quantidade de adversários antes de ser eliminado.",
    equipment: "Equipamentos individuais previamente definidos pela organização para manter equilíbrio entre os duelos.",
    safety: "A arena deve possuir espaço suficiente para o duelo, mantendo os demais participantes fora da área ativa até sua vez de entrar.",
  },
];

export const demoPosts: Post[] = [
  {
    id: "post-1",
    title: "Treino do DK — 13/09/2026",
    slug: "treino-dk-13-09-2026",
    excerpt: "Registros, destaques e momentos do retorno às atividades do DK.",
    content:
      "Depois de um breve intervalo, o DK voltou ao campo para mais uma manhã de treino, integração e evolução técnica. A atividade reuniu membros e novos participantes em exercícios, duelos e jogos coletivos.",
    category: "Treinos",
    cover_url: null,
    published: true,
    published_at: "2026-09-13T14:00:00-03:00",
    media_items: [],
  },
  {
    id: "post-2",
    title: "Participação em evento geek",
    slug: "participacao-evento-geek",
    excerpt: "O DK levou demonstrações e experiências de Swordplay para o público.",
    content:
      "A equipe apresentou equipamentos, regras básicas e atividades adaptadas para quem conheceu o Swordplay pela primeira vez.",
    category: "Eventos",
    cover_url: null,
    published: true,
    published_at: "2026-08-30T18:00:00-03:00",
    media_items: [],
  },
];
